# Generated by Django 4.1.2 on 2022-11-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_url_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
