# Generated by Django 4.1.2 on 2022-11-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0003_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(),
        ),
    ]
