# Generated by Django 4.1.2 on 2022-12-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0004_alter_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='last_ping_status_code',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
