# Generated by Django 4.1.2 on 2022-12-11 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0005_url_last_ping_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='last_ping_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
