# Generated by Django 4.1.2 on 2022-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0006_url_last_ping_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='last_ping_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='last_ping_status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
