# Generated by Django 4.1.2 on 2022-12-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0007_alter_url_last_ping_date_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ('id',)},
        ),
    ]
