# Generated by Django 4.1.2 on 2022-12-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0008_alter_url_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='last_ping_date_time',
            new_name='last_alert_date_time',
        ),
    ]
