# Generated by Django 4.1.9 on 2023-06-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0009_rename_last_ping_date_time_url_last_alert_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
