# Generated by Django 4.1.9 on 2023-06-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0010_alter_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
