# Generated by Django 4.1.2 on 2022-11-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
