# Generated by Django 4.1.2 on 2022-12-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_phone_verified_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
