# Generated by Django 4.1.9 on 2023-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_phone_otp_user_phone_otp_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_google_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
