# Generated by Django 4.1.10 on 2023-04-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_google_refresh_token_user_linked_google_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linked_google_email',
        ),
    ]
