# Generated by Django 4.1.2 on 2022-11-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount_paid',
            new_name='amount',
        ),
    ]
