# Generated by Django 4.1.2 on 2022-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_amount_paid_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_url',
            field=models.URLField(null=True),
        ),
    ]
