# Generated by Django 4.1.2 on 2022-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_invoice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_url',
            field=models.URLField(),
        ),
    ]
