# Generated by Django 4.1.10 on 2023-07-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_domain_is_subscription_active_and_more'),
        ('invoices', '0004_alter_invoice_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain'),
        ),
    ]
