# Generated by Django 4.1.2 on 2022-11-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='allowed_domains',
            field=models.PositiveIntegerField()
        ),
        migrations.AddField(
            model_name='plan',
            name='allowed_urls',
            field=models.PositiveIntegerField()
        ),
        migrations.AddField(
            model_name='plan',
            name='allowed_users',
            field=models.PositiveIntegerField()
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
    ]
