# Generated by Django 4.1.2 on 2022-11-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_frequency_remove_plan_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
