# Generated by Django 4.1.2 on 2022-11-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plan_stripe_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('id',)},
        ),
    ]
