# Generated by Django 4.1.2 on 2022-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_price_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ping_interval',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
