# Generated by Django 4.1.10 on 2023-07-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_plan_ping_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='allowed_domains',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='allowed_users',
        ),
    ]
