# Generated by Django 4.1.10 on 2023-07-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_plan_allowed_domains_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='ping_interval',
        ),
    ]
