# Generated by Django 4.1.10 on 2023-07-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_remove_plan_ping_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('id',)},
        ),
    ]
