# Generated by Django 4.1.2 on 2022-11-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domain_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_url',
            field=models.URLField(unique=True),
        ),
    ]
