# Generated by Django 4.1.2 on 2022-11-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_alter_domain_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_url',
            field=models.URLField(),
        ),
    ]
