# Generated by Django 4.1.2 on 2022-12-18 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0004_alter_domain_domain_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
