# Generated by Django 4.1.2 on 2022-12-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_domain_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('id',)},
        ),
    ]
