# Generated by Django 4.1.10 on 2023-07-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_plan_allowed_domains_and_more'),
        ('domains', '0007_alter_domain_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='subscribed_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.price'),
        ),
    ]
