# Generated by Django 4.1.10 on 2023-07-22 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_domain_is_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='alert_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
    ]
