# Generated by Django 4.1.10 on 2023-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_domain_alert_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
