# Generated by Django 4.1.2 on 2022-11-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
