# Generated by Django 4.1.2 on 2022-11-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_description'),
        ('companies', '0003_company_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscribed_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.price'),
        ),
    ]
