# Generated by Django 4.1.2 on 2022-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
