# Generated by Django 4.1.2 on 2022-12-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='downloadable_file_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
