# Generated by Django 4.1.7 on 2023-04-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_downloadable_file_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linked_google_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
