# Generated by Django 4.1.10 on 2023-07-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_subscription_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subscribed_plan',
        ),
    ]
